[platformio]
default_envs = esp32_usb

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    marcoschwartz/LiquidCrystal_I2C
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BME280 Library
    witnessmenow/UniversalTelegramBot
    bblanchon/ArduinoJson @ ^6.21.5
    knolleary/PubSubClient

; --- ПРОФІЛЬ ДЛЯ КАБЕЛЮ ---
[env:esp32_usb]
upload_protocol = esptool
upload_port = /dev/cu.usbserial-0001

; --- ПРОФІЛЬ ДЛЯ WI-FI (OTA) ---
[env:esp32_ota]
upload_protocol = espota
upload_port = SmartGarden-ESP32.local
upload_flags =
  --timeout=30